[versions]
activityCompose = "1.8.2"
androidx-junit = "1.1.5"
coil = "2.4.0"
coreKtx = "1.12.0"
coreSplashscreen = "1.0.1"
espressoCore = "3.5.1"
javapoet = "1.13.0"
junit = "4.13.2"
kotlin = "1.9.21"
ksp = "1.9.21-1.0.16"
android-gradle-plugin = "8.2.0"
google-services-version = "4.4.0"
hilt = "2.48"
hiltExt = "1.1.0"
timber = "5.0.1"
lifecycleRuntimeKtx = "2.6.2"
phitoArch = "0.4.1"
gradle-versions = "0.48.0"
uiTestJunit4 = "1.5.4"
version-catalog-update = "0.8.1"
turbine = "1.0.0"
composeBom = "2023.10.01"
dataStore = "1.0.0"
protobuf-gradle-plugin = "0.9.4"
protobuf = "3.24.4"
grpc = "1.59.0"
grpcKotlin = "1.4.0"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
google-services = { module = "com.google.gms:google-services", version.ref = "google-services-version" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltExt" }
javapoet = { module = "com.squareup:javapoet", version.ref = "javapoet" }
junit = { module = "junit:junit", version.ref = "junit" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
phito-arch = { module = "com.ralphdugue:phito-arch", version.ref = "phitoArch" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "uiTestJunit4" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
dataStore = { module = "androidx.datastore:datastore-preferences", version.ref = "dataStore" }
protobuf-javalite = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
protobuf-kotlin = { module = "com.google.protobuf:protobuf-kotlin", version.ref = "protobuf" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
grpc-kotlin-stub = { module = "io.grpc:grpc-kotlin-stub", version.ref = "grpcKotlin" }
protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
grpc-okhttp = { module = "io.grpc:grpc-okhttp", version.ref = "grpc" }

[bundles]
hilt = ["hilt-android", "hilt-navigation-compose", "hilt-android-gradle-plugin"]
hilt-ksp = ["hilt-compiler", "dagger-compiler"]
coil = ["coil", "coil-compose"]
androidx = ["core-ktx", "core-splashscreen", "activity-compose", "lifecycle-runtime-ktx", "dataStore"]
androidx-test = ["ext-junit", "espresso-core", "ui-test-junit4"]
test = ["junit", "turbine"]
grpc = ["grpc-stub", "grpc-kotlin-stub", "protobuf-kotlin", "protobuf", "protobuf-javalite"]

[plugins]
android-app = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services-version" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
gradle-versions = { id = "com.github.ben-manes.versions", version.ref = "gradle-versions" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-gradle-plugin" }

